### ISSUE TITLE
Search is blocked by this

### ISSUE THREAD

**Issue by noididntreadit** [thomaswangio/minimal-twitter#1]
I love the cleaner UI but I went to search (or "explore", ugh) and the search bar is gone. Is it possible to sneak that through without allowing the crap to return?

With extension:
![image](https://user-images.githubusercontent.com/49111837/61667710-58702480-aca0-11e9-8d5d-da21e03b30a4.png)

Incognito (no extension):
![image](https://user-images.githubusercontent.com/49111837/61667752-776eb680-aca0-11e9-9a1f-77290fcfed48.png)

Both are https://twitter.com/explore.

**Comment by thomaswangio** [comment]
@noididntreadit  It's actually anchored to the top right, can you see if it's there on your browser?

**Comment by thomaswangio** [comment]
@noididntreadit On second thought you're right, it would probably better if it was in the right place, centered on the explore page. I'll make that the default in the next update!

**Comment by thomaswangio** [comment]
@noididntreadit this commit addresses this issue! https://github.com/thomaswangio/minimal-twitter/commit/d3123ddad24fee3918a73c8a612d3e15d057b32b

Check back for the next update and it should be fixed :) thanks for pointing this out
