### ISSUE TITLE
Options disabled on Chrome

### ISSUE THREAD

**Issue by JaxonWright** [thomaswangio/minimal-twitter#14]
When I right-click the extension, _Options_ is disabled. 

What do I have to do to get it working?

**Comment by thomaswangio** [comment]
Hey @JaxonWright are you using the new Chrome extension? https://chrome.google.com/webstore/detail/minimal-twitter/pobhoodpcipjmedfenaigbeloiidbflp

I had to unpublish version 1 from the Chrome Web Store because of some update issues

**Comment by JaxonWright** [comment]
That is the reason. Thanks!
