### ISSUE TITLE
Search bar on explore cuts off text

### ISSUE THREAD

**Issue by thomaswangio** [thomaswangio/minimal-twitter#15]
Bug or feature? Need to target explore search specially when not focused needs to have 100% width

**Comment by 50kudos** [comment]
Not sure why it has to have a specific width since its `form[aria-label="Search Twitter"][role="search"]` already has the max width.

If I'm not missing something, this should do it:
```diff
input[placeholder="Search Twitter"] {
  padding-left: 34px !important;
  margin-left: -24px !important;
  z-index: 1 !important;
- width: 150px !important;
  transition: 0.5s cubic-bezier(0.2, 0.8, 0.2, 1);
}
```

**Comment by thomaswangio** [comment]
Ah, thanks for commenting @50kudos, but i'm using the width to help with the transition effect with the search field and to keep it out of the way more.

I did fix this issue here: https://github.com/thomaswangio/minimal-twitter/commit/6341c4dd06ce258439af1afc5f3ea37c41b72d2a

Upgraded to 2.6 :)
