### ISSUE TITLE
make content area wider

### ISSUE THREAD

**Issue by Stanzilla** [thomaswangio/minimal-twitter#16]
Is it possible to make the center area (the feed) a bit wider?

**Comment by thomaswangio** [comment]
Hey @Stanzilla you can set it in preferences up to 800px! https://github.com/thomaswangio/minimal-twitter#chrome-and-firefox-preferences

Let me know if this works for you?

**Comment by Stanzilla** [comment]
Oh guess I missed that, that's better, thank you!
