### ISSUE TITLE
Customize/disable the shortcut

### ISSUE THREAD

**Issue by alexpolozov** [thomaswangio/minimal-twitter#17]
`Ctrl+Shift+T` in Chrome is mapped to "Reopen last closed tab" by default — a vitally important feature which I use several times per day. It's in my muscle memory now. This extension silently overrides it to open Twitter without any way to customize or disable this. Is it possible to change that?

**Comment by thomaswangio** [comment]
Hey @alexpolozov I changed the Windows shortcut to `Alt+Shift+T` in the latest version (2.9). Sorry for the late reply thanks for catching this!

**Comment by alexpolozov** [comment]
Thank you @thomaswangio!
