### ISSUE TITLE
Add option to top-align navigation

### ISSUE THREAD

**Issue by JaxonWright** [thomaswangio/minimal-twitter#6]
Love the extension, but it would be really nice to be able to top-align the navigation buttons.

**Comment by thomaswangio** [comment]
done! https://github.com/thomaswangio/minimal-twitter/commit/a0d91550f2c5fa11534267c67d412ba3e01a7ad5

also thanks to @T0astBread for porting the options to Firefox... I couldn't figure out the manifest 😓
