### ISSUE TITLE
"Search Twitter" placeholder cropped on Firefox (1920x1080)

### ISSUE THREAD

**Issue by akien-mga** [thomaswangio/minimal-twitter#8]
I just installed version 2.4 on Firefox Nightly. The "Search Twitter" placeholder text in the search bar is cropped, so the "r" is missing:

![Screenshot_20190725_125950](https://user-images.githubusercontent.com/4701338/61869632-5db9b300-aedc-11e9-8e21-4cb32f2201c5.png)

**Comment by akien-mga** [comment]
I just found out that the font size is configurable in the Twitter settings. So the above issue happens with the default font size (second notch). With the minimal font size (first notch) it seems ok.

![Screenshot_20190725_141658](https://user-images.githubusercontent.com/4701338/61873699-dfaed980-aee6-11e9-90fe-c2219ce2d0ff.png)

**Comment by thomaswangio** [comment]
Hey @akien-mga thanks for pointing out this bug, I fixed here! https://github.com/thomaswangio/minimal-twitter/commit/af4b2b25c99ad3c23acf165172d633bb83481281

**Comment by enebo** [comment]
@thomaswang I have a reduced size window on my 3400x1200ish screen.  It is probably about 1100 pixels wide and the search shows up once it is 1200 or maybe 1300 wide.  So until I found this issue I could not find the search.  Would be be a horrible ask to consider laying out search on left hand side with other navigation?

**Comment by thomaswang** [comment]
Hey @enebo if you need to search with a smaller window size, you could click on the "explore tab" and do the search there.

**Comment by enebo** [comment]
@thomaswang amazingly that search dialogue will also not show up unless I reduce or enlarge the window size.  It seems to not display between a width ~1200px to about ~900px.

**Comment by thomaswang** [comment]
@enebo thanks for catching that! I fixed the bug and pushed a new version to Firefox: https://addons.mozilla.org/en-US/firefox/addon/min-twitter/

**Comment by enebo** [comment]
@thomaswang thanks it is there again for explore AND it looks like on main page it also is now present until the page is collapsed to perhaps 800px.  So that also improved as well!
